on:
  push:
    branches: [main]
  pull_request:

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os:
          # Linux x86_64
          - ubuntu-latest
          # Mac aarch64
          - macos-latest
          # Windows x86_64
          - windows-latest
        python_version: ["3.9", "3.14", "graalpy@3.12"]
        exclude:
          # GraalPy's ctypes on Windows doesn't support the calls filelock uses
          - os: windows-latest
            python_version: "graalpy@3.12"
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
      - name: Bootstrap Rust
        run: uv run -p ${{ matrix.python_version }} python -m puccinialin

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Ruff lint
        uses: astral-sh/ruff-action@f2e32211077f40bfeab40e16285216924ebea4cb # v2.0.0
        with:
          args: "check"
      - name: Ruff format
        uses: astral-sh/ruff-action@f2e32211077f40bfeab40e16285216924ebea4cb # v2.0.0
        with:
          args: "format --check"
      - name: Prettier
        run: npx prettier --check --print-width 120 --prose-wrap always .github/** src/** *.md
      - uses: astral-sh/setup-uv@d4b2f3b6ecc6e67c4457f6d3e41ec42d3d0fcb86 # v5.4.2
      - name: Type Check
        run: uv run ty check
